from fastapi import APIRouter, Depends, Query, Response, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.v1.deps import get_current_user, require_permission
from app.core.auth_cookies import set_auth_cookie, set_refresh_cookie
from app.db.session import get_db
from app.models import User
from app.schemas.organization_invitation_schemas import (
    AcceptInvitationRequest,
    CreateOrganizationInvitationRequest,
    InvitationListResponse,
    InvitationResponse,
    InvitationStatusResponse,
    InviteUserResponse,
    NewOrganizationInviteResponse,
    OrganizationInviteRequest,
)
from app.services.invitation_service import (
    accept_organization_invitation,
    cancel_organization_invitation,
    create_new_organization_invitation,
    create_organization_user_invitation,
    get_and_validate_invitation_by_token,
    list_organization_invitations,
    resend_organization_invitation,
)

router = APIRouter()


# 1. GET /api/v1/organizations/invitations - List invitations (Protected)
@router.get(
    "",
    response_model=InvitationListResponse,
    summary="List Organization Invitations",
    dependencies=[Depends(require_permission("invitations:read"))],
)
async def list_invitations(
    search: str | None = Query(None, description="Search by email or full name"),
    status: str | None = Query(
        None, description="Filter by status: Pending, Accepted, Expired, Cancelled"
    ),
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    sort_by: str = Query("created_at", description="Sort by created_at, email, status"),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    return await list_organization_invitations(
        db=db,
        current_user=current_user,
        search=search,
        status_filter=status,
        page=page,
        limit=limit,
        sort_by=sort_by,
    )


# 2. POST /api/v1/organizations/invitations - Invite additional users (Protected)
@router.post(
    "",
    response_model=InviteUserResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Invite Additional User to Organization",
    dependencies=[Depends(require_permission("invitations:create"))],
)
async def invite_user(
    payload: OrganizationInviteRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    return await create_organization_user_invitation(db, payload, current_user)


# 2b. POST /api/v1/organizations/invitations/new-organization - Invite a brand-new organization (Protected)
@router.post(
    "/new-organization",
    response_model=NewOrganizationInviteResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Invite a New Organization",
    description=(
        "Creates a brand-new organization (ID generated by the backend), links a pending "
        "invitation to it, and emails the invitee. The request body never contains an "
        "organization_id — a client-supplied org ID is not accepted."
    ),
    dependencies=[
        Depends(require_permission("organization:update")),
        Depends(require_permission("invitations:create")),
    ],
)
async def invite_new_organization(
    payload: CreateOrganizationInvitationRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    return await create_new_organization_invitation(db, payload, current_user)


# 3. GET /api/v1/organizations/invitations/{token} - Validate invitation (PUBLIC)
@router.get(
    "/{token}",
    response_model=InvitationStatusResponse,
    summary="Validate Invitation Token (Public)",
)
async def validate_invitation(token: str, db: AsyncSession = Depends(get_db)):
    """
    Public endpoint: Validates invitation token, expiration, status, and organization status.
    Returns 410 if expired, 400 if accepted/cancelled, 403 if organization/subscription inactive.
    """
    return await get_and_validate_invitation_by_token(db, token)


# 4. POST /api/v1/organizations/invitations/{token}/accept - Accept invitation (PUBLIC)
@router.post("/{token}/accept", summary="Accept Invitation & Complete Registration (Public)")
async def accept_invitation(
    token: str,
    payload: AcceptInvitationRequest,
    response: Response,
    db: AsyncSession = Depends(get_db),
):
    """
    Public endpoint: Accepts invitation, hashes password, activates Organization Admin user,
    writes audit log, and returns JWT access token.
    """
    result = await accept_organization_invitation(db, token, payload)
    set_auth_cookie(response, result["access_token"])
    set_refresh_cookie(response, result["refresh_token"])
    return {
        key: value
        for key, value in result.items()
        if key not in {"access_token", "refresh_token"}
    }


# 5. POST /api/v1/organizations/invitations/{id}/resend - Resend invitation (Protected)
@router.post(
    "/{id}/resend",
    response_model=InvitationResponse,
    summary="Resend Organization Invitation",
    dependencies=[Depends(require_permission("invitations:resend"))],
)
async def resend_invitation(
    id: str, db: AsyncSession = Depends(get_db), current_user: User = Depends(get_current_user)
):
    return await resend_organization_invitation(db, invitation_id=id, current_user=current_user)


# 6. POST /api/v1/organizations/invitations/{id}/cancel - Cancel invitation (Protected)
@router.post(
    "/{id}/cancel",
    summary="Cancel Organization Invitation",
    dependencies=[Depends(require_permission("invitations:revoke"))],
)
async def cancel_invitation(
    id: str, db: AsyncSession = Depends(get_db), current_user: User = Depends(get_current_user)
):
    return await cancel_organization_invitation(db, invitation_id=id, current_user=current_user)
