"""add missing leads columns

Revision ID: 39346817277b
Revises: f8a832876815
Create Date: 2026-08-03 23:31:36.941554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39346817277b'
down_revision: Union[str, Sequence[str], None] = 'f8a832876815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_attachments', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('lead_attachments', sa.Column('mime_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_attachments', 'mime_type')
    op.drop_column('lead_attachments', 'file_size')
    # ### end Alembic commands ###
