"""add organization invitations

Revision ID: 4accd07da9c5
Revises: b88877665544
Create Date: 2026-08-06 10:43:45.391438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4accd07da9c5'
down_revision: Union[str, Sequence[str], None] = 'b88877665544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_invitations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Monthly'::character varying"))
    op.alter_column('organization_subscriptions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('organization_subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'INR'::character varying"))
    op.alter_column('organization_subscriptions', 'trial',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('organization_subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('organization_subscriptions', 'max_users',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('organization_subscriptions', 'current_users',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('organization_subscriptions', 'storage_limit_gb',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('500'))
    op.alter_column('organization_subscriptions', 'storage_used_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('organization_subscriptions', 'ai_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('organization_subscriptions', 'support_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Standard'::character varying"))
    op.alter_column('organization_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_organization_subscriptions_organization_id'), table_name='organization_subscriptions')
    op.create_index(op.f('ix_organization_subscriptions_organization_id'), 'organization_subscriptions', ['organization_id'], unique=True)
    op.drop_column('organization_subscriptions', 'plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_subscriptions', sa.Column('plan', sa.VARCHAR(length=50), server_default=sa.text("'Enterprise'::character varying"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_organization_subscriptions_organization_id'), table_name='organization_subscriptions')
    op.create_index(op.f('ix_organization_subscriptions_organization_id'), 'organization_subscriptions', ['organization_id'], unique=False)
    op.alter_column('organization_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_subscriptions', 'support_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Standard'::character varying"))
    op.alter_column('organization_subscriptions', 'ai_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('organization_subscriptions', 'storage_used_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('organization_subscriptions', 'storage_limit_gb',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('500'))
    op.alter_column('organization_subscriptions', 'current_users',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('organization_subscriptions', 'max_users',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('organization_subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('organization_subscriptions', 'trial',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('organization_subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'INR'::character varying"))
    op.alter_column('organization_subscriptions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('organization_subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Monthly'::character varying"))
    op.alter_column('organization_invitations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
