"""bootstrap the historical SQLAlchemy schema

Revision ID: 8a1b2c3d4e5f
Revises: 7fcd8359c9f2
"""

from alembic import op

revision: str = "8a1b2c3d4e5f"
down_revision = "7fcd8359c9f2"
branch_labels = None
depends_on = None

_BASELINE_DDL = [
    "CREATE TABLE IF NOT EXISTS countries (\n\tid VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tiso_code VARCHAR(10) NOT NULL, \n\tphone_code VARCHAR(20), \n\tPRIMARY KEY (id), \n\tUNIQUE (iso_code)\n)",
    "CREATE TABLE IF NOT EXISTS currencies (\n\tid VARCHAR NOT NULL, \n\tcode VARCHAR(10) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tsymbol VARCHAR(10) NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "CREATE TABLE IF NOT EXISTS file_uploads (\n\tid VARCHAR NOT NULL, \n\tfilename VARCHAR(255) NOT NULL, \n\tfile_path VARCHAR(500) NOT NULL, \n\tfile_size INTEGER NOT NULL, \n\tmime_type VARCHAR(100) NOT NULL, \n\tuploaded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "CREATE TABLE IF NOT EXISTS languages (\n\tid VARCHAR NOT NULL, \n\tcode VARCHAR(10) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "CREATE TABLE IF NOT EXISTS organizations (\n\tid VARCHAR NOT NULL, \n\tname VARCHAR(255) NOT NULL, \n\tdomain VARCHAR(255), \n\tplan VARCHAR(100) NOT NULL, \n\tmax_users INTEGER NOT NULL, \n\tis_active BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "CREATE TABLE IF NOT EXISTS permissions (\n\tid VARCHAR NOT NULL, \n\tmodule VARCHAR(100) NOT NULL, \n\taction VARCHAR(100) NOT NULL, \n\tdescription TEXT, \n\tPRIMARY KEY (id)\n)",
    "CREATE TABLE IF NOT EXISTS settings (\n\tid VARCHAR NOT NULL, \n\tkey VARCHAR(100) NOT NULL, \n\tvalue TEXT NOT NULL, \n\tdescription TEXT, \n\tPRIMARY KEY (id)\n)",
    "CREATE TABLE IF NOT EXISTS timezones (\n\tid VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tutc_offset VARCHAR(20) NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "CREATE TABLE IF NOT EXISTS user_invitations (\n\tid VARCHAR NOT NULL, \n\temail VARCHAR(255) NOT NULL, \n\ttoken VARCHAR(255) NOT NULL, \n\trole VARCHAR(100) NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tstatus VARCHAR(50) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "CREATE TABLE IF NOT EXISTS api_keys (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tkey_hash VARCHAR(255) NOT NULL, \n\tscopes TEXT, \n\tis_active BOOLEAN NOT NULL, \n\tlast_used TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS companies (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tname VARCHAR(255) NOT NULL, \n\tindustry VARCHAR(100), \n\twebsite VARCHAR(255), \n\temployee_count INTEGER, \n\tparent_company_id VARCHAR, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(parent_company_id) REFERENCES companies (id) ON DELETE SET NULL\n)",
    "CREATE TABLE IF NOT EXISTS contacts (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tname VARCHAR(255) NOT NULL, \n\temail VARCHAR(255) NOT NULL, \n\tphone VARCHAR(50), \n\tposition VARCHAR(100), \n\tcompany_id VARCHAR, \n\tis_starred BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS deal_stages (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tdefault_probability FLOAT NOT NULL, \n\torder_index INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS email_templates (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tname VARCHAR(255) NOT NULL, \n\tsubject VARCHAR(500) NOT NULL, \n\tbody_template TEXT NOT NULL, \n\tcategory VARCHAR(100), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS emails (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tfrom_email VARCHAR(255) NOT NULL, \n\tto_email VARCHAR(255) NOT NULL, \n\tsubject VARCHAR(500) NOT NULL, \n\tbody_text TEXT, \n\tbody_html TEXT, \n\tstatus VARCHAR(50) NOT NULL, \n\tsent_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS integrations (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tis_connected BOOLEAN NOT NULL, \n\taccess_token TEXT, \n\trefresh_token TEXT, \n\tlast_synced TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS lead_sources (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS lead_statuses (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\torder_index INTEGER NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS meetings (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\ttitle VARCHAR(255) NOT NULL, \n\tdescription TEXT, \n\tstart_time TIMESTAMP WITH TIME ZONE NOT NULL, \n\tend_time TIMESTAMP WITH TIME ZONE NOT NULL, \n\tmeeting_link VARCHAR(500), \n\tai_summary TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS organization_settings (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tprimary_color VARCHAR(50) NOT NULL, \n\tlogo_url VARCHAR(500), \n\ttimezone VARCHAR(100) NOT NULL, \n\tcurrency VARCHAR(10) NOT NULL, \n\tlanguage VARCHAR(10) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS organization_subscriptions (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tstripe_customer_id VARCHAR(255), \n\tstripe_subscription_id VARCHAR(255), \n\tstatus VARCHAR(50) NOT NULL, \n\tcurrent_period_start TIMESTAMP WITH TIME ZONE, \n\tcurrent_period_end TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS product_categories (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tdescription TEXT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS roles (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR, \n\tname VARCHAR(100) NOT NULL, \n\tdescription TEXT, \n\tis_system_role BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS states (\n\tid VARCHAR NOT NULL, \n\tcountry_id VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tstate_code VARCHAR(20), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(country_id) REFERENCES countries (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS users (\n\tid VARCHAR NOT NULL, \n\tname VARCHAR(255) NOT NULL, \n\temail VARCHAR(255) NOT NULL, \n\thashed_password VARCHAR(255) NOT NULL, \n\trole VARCHAR(100) NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tis_active BOOLEAN NOT NULL, \n\tis_verified BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS webhooks (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\ttarget_url VARCHAR(500) NOT NULL, \n\tevents TEXT NOT NULL, \n\tsecret VARCHAR(255), \n\tis_active BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS activity_logs (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\tmodule VARCHAR(100) NOT NULL, \n\taction_description TEXT NOT NULL, \n\ttimestamp TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS ai_conversations (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\ttitle VARCHAR(255), \n\tmodel_name VARCHAR(100) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS ai_generated_contents (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\tcontent_type VARCHAR(50) NOT NULL, \n\tgenerated_text TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS ai_meeting_summaries (\n\tid VARCHAR NOT NULL, \n\tmeeting_id VARCHAR NOT NULL, \n\tsummary_text TEXT NOT NULL, \n\taction_items_json TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS audit_logs (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR, \n\tuser_id VARCHAR, \n\taction VARCHAR(100) NOT NULL, \n\tip_address VARCHAR(45), \n\tdetails TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL\n)",
    "CREATE TABLE IF NOT EXISTS calendar_events (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\ttitle VARCHAR(255) NOT NULL, \n\tdescription TEXT, \n\tstart_time TIMESTAMP WITH TIME ZONE NOT NULL, \n\tend_time TIMESTAMP WITH TIME ZONE NOT NULL, \n\tevent_type VARCHAR(50) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS call_logs (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tcontact_id VARCHAR NOT NULL, \n\tcall_type VARCHAR(50) NOT NULL, \n\tduration_seconds INTEGER NOT NULL, \n\tnotes TEXT, \n\trecording_url VARCHAR(500), \n\tdisposition VARCHAR(100), \n\ttimestamp TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(contact_id) REFERENCES contacts (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS cities (\n\tid VARCHAR NOT NULL, \n\tstate_id VARCHAR NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(state_id) REFERENCES states (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS company_contacts (\n\tid VARCHAR NOT NULL, \n\tcompany_id VARCHAR NOT NULL, \n\tcontact_id VARCHAR NOT NULL, \n\trole_in_company VARCHAR(100), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(company_id) REFERENCES companies (id) ON DELETE CASCADE, \n\tFOREIGN KEY(contact_id) REFERENCES contacts (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS contact_addresses (\n\tid VARCHAR NOT NULL, \n\tcontact_id VARCHAR NOT NULL, \n\tstreet VARCHAR(255), \n\tcity VARCHAR(100), \n\tstate VARCHAR(100), \n\tcountry VARCHAR(100), \n\tpostal_code VARCHAR(20), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(contact_id) REFERENCES contacts (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS contact_tags (\n\tid VARCHAR NOT NULL, \n\tcontact_id VARCHAR NOT NULL, \n\ttag_name VARCHAR(100) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(contact_id) REFERENCES contacts (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS deals (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\ttitle VARCHAR(255) NOT NULL, \n\tamount FLOAT NOT NULL, \n\tstage VARCHAR(100) NOT NULL, \n\tprobability FLOAT NOT NULL, \n\texpected_close_date TIMESTAMP WITH TIME ZONE, \n\tassigned_to VARCHAR NOT NULL, \n\tcontact_id VARCHAR, \n\tcompany_id VARCHAR, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assigned_to) REFERENCES users (id) ON DELETE CASCADE, \n\tFOREIGN KEY(contact_id) REFERENCES contacts (id) ON DELETE SET NULL, \n\tFOREIGN KEY(company_id) REFERENCES companies (id) ON DELETE SET NULL\n)",
    "CREATE TABLE IF NOT EXISTS documents (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tfolder_id VARCHAR, \n\tfilename VARCHAR(255) NOT NULL, \n\tfile_size INTEGER NOT NULL, \n\tmime_type VARCHAR(100) NOT NULL, \n\tfile_url VARCHAR(500) NOT NULL, \n\tuploaded_by VARCHAR NOT NULL, \n\tuploaded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(uploaded_by) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS email_logs (\n\tid VARCHAR NOT NULL, \n\temail_id VARCHAR NOT NULL, \n\tevent_type VARCHAR(50) NOT NULL, \n\tuser_agent TEXT, \n\ttimestamp TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(email_id) REFERENCES emails (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS email_verifications (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\ttoken VARCHAR(255) NOT NULL, \n\tis_verified BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS leads (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\ttitle VARCHAR(255) NOT NULL, \n\tcompany VARCHAR(255) NOT NULL, \n\tcontact_name VARCHAR(255) NOT NULL, \n\temail VARCHAR(255) NOT NULL, \n\tphone VARCHAR(50), \n\tstatus VARCHAR(100) NOT NULL, \n\tsource VARCHAR(100), \n\tscore FLOAT NOT NULL, \n\tassigned_to VARCHAR, \n\tis_archived BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assigned_to) REFERENCES users (id) ON DELETE SET NULL\n)",
    "CREATE TABLE IF NOT EXISTS meeting_attendees (\n\tid VARCHAR NOT NULL, \n\tmeeting_id VARCHAR NOT NULL, \n\temail VARCHAR(255) NOT NULL, \n\tname VARCHAR(255), \n\trsvp_status VARCHAR(50) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS notes (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tentity_type VARCHAR(50) NOT NULL, \n\tentity_id VARCHAR NOT NULL, \n\tcontent TEXT NOT NULL, \n\tis_pinned BOOLEAN NOT NULL, \n\tcreated_by VARCHAR NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(created_by) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS notifications (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\ttitle VARCHAR(255) NOT NULL, \n\tmessage TEXT NOT NULL, \n\tis_read BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS otp_verifications (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\totp_code VARCHAR(10) NOT NULL, \n\tsecret_key VARCHAR(255), \n\tis_used BOOLEAN NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS password_resets (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\ttoken VARCHAR(255) NOT NULL, \n\tis_used BOOLEAN NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS products (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tcategory_id VARCHAR, \n\tname VARCHAR(255) NOT NULL, \n\tsku VARCHAR(100) NOT NULL, \n\tprice FLOAT NOT NULL, \n\tin_stock_quantity INTEGER NOT NULL, \n\tis_active BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(category_id) REFERENCES product_categories (id) ON DELETE SET NULL\n)",
    "CREATE TABLE IF NOT EXISTS refresh_tokens (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\ttoken VARCHAR(500) NOT NULL, \n\tis_revoked BOOLEAN NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS report_exports (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\treport_type VARCHAR(100) NOT NULL, \n\tfile_format VARCHAR(20) NOT NULL, \n\tdownload_url VARCHAR(500) NOT NULL, \n\trequested_by VARCHAR NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(requested_by) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS role_permissions (\n\tid VARCHAR NOT NULL, \n\trole_id VARCHAR NOT NULL, \n\tpermission_id VARCHAR NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE, \n\tFOREIGN KEY(permission_id) REFERENCES permissions (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS tasks (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\ttitle VARCHAR(255) NOT NULL, \n\tdescription TEXT, \n\tpriority VARCHAR(50) NOT NULL, \n\tstatus VARCHAR(50) NOT NULL, \n\tdue_date TIMESTAMP WITH TIME ZONE NOT NULL, \n\tassigned_to VARCHAR NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assigned_to) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS user_profiles (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\tphone_number VARCHAR(50), \n\tavatar_url VARCHAR(500), \n\tbio TEXT, \n\tjob_title VARCHAR(100), \n\tdepartment VARCHAR(100), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS user_roles (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\trole_id VARCHAR NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, \n\tFOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS user_sessions (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\tdevice_info VARCHAR(255), \n\tip_address VARCHAR(45), \n\tuser_agent TEXT, \n\tis_current BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS ai_lead_scores (\n\tid VARCHAR NOT NULL, \n\tlead_id VARCHAR NOT NULL, \n\tscore FLOAT NOT NULL, \n\tconfidence FLOAT NOT NULL, \n\treasons_json TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(lead_id) REFERENCES leads (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS ai_prompts (\n\tid VARCHAR NOT NULL, \n\tconversation_id VARCHAR NOT NULL, \n\tuser_prompt TEXT NOT NULL, \n\tai_response TEXT NOT NULL, \n\ttokens_used INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(conversation_id) REFERENCES ai_conversations (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS deal_activities (\n\tid VARCHAR NOT NULL, \n\tdeal_id VARCHAR NOT NULL, \n\taction VARCHAR(255) NOT NULL, \n\tperformed_by VARCHAR, \n\ttimestamp TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(deal_id) REFERENCES deals (id) ON DELETE CASCADE, \n\tFOREIGN KEY(performed_by) REFERENCES users (id) ON DELETE SET NULL\n)",
    "CREATE TABLE IF NOT EXISTS deal_products (\n\tid VARCHAR NOT NULL, \n\tdeal_id VARCHAR NOT NULL, \n\tproduct_id VARCHAR NOT NULL, \n\tquantity INTEGER NOT NULL, \n\tunit_price FLOAT NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(deal_id) REFERENCES deals (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS document_versions (\n\tid VARCHAR NOT NULL, \n\tdocument_id VARCHAR NOT NULL, \n\tversion_number INTEGER NOT NULL, \n\tfile_url VARCHAR(500) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(document_id) REFERENCES documents (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS lead_activities (\n\tid VARCHAR NOT NULL, \n\tlead_id VARCHAR NOT NULL, \n\taction VARCHAR(255) NOT NULL, \n\tperformed_by VARCHAR, \n\ttimestamp TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(lead_id) REFERENCES leads (id) ON DELETE CASCADE, \n\tFOREIGN KEY(performed_by) REFERENCES users (id) ON DELETE SET NULL\n)",
    "CREATE TABLE IF NOT EXISTS lead_attachments (\n\tid VARCHAR NOT NULL, \n\tlead_id VARCHAR NOT NULL, \n\tfilename VARCHAR(255) NOT NULL, \n\tfile_url VARCHAR(500) NOT NULL, \n\tuploaded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(lead_id) REFERENCES leads (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS lead_notes (\n\tid VARCHAR NOT NULL, \n\tlead_id VARCHAR NOT NULL, \n\tcontent TEXT NOT NULL, \n\tcreated_by VARCHAR NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(lead_id) REFERENCES leads (id) ON DELETE CASCADE, \n\tFOREIGN KEY(created_by) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS lead_scores (\n\tid VARCHAR NOT NULL, \n\tlead_id VARCHAR NOT NULL, \n\tscore FLOAT NOT NULL, \n\treason_factors TEXT, \n\tcalculated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(lead_id) REFERENCES leads (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS lead_tags (\n\tid VARCHAR NOT NULL, \n\tlead_id VARCHAR NOT NULL, \n\ttag_name VARCHAR(100) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(lead_id) REFERENCES leads (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS quotes (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tdeal_id VARCHAR, \n\tquote_number VARCHAR(100) NOT NULL, \n\ttotal_amount FLOAT NOT NULL, \n\tstatus VARCHAR(50) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(deal_id) REFERENCES deals (id) ON DELETE SET NULL\n)",
    "CREATE TABLE IF NOT EXISTS task_attachments (\n\tid VARCHAR NOT NULL, \n\ttask_id VARCHAR NOT NULL, \n\tfilename VARCHAR(255) NOT NULL, \n\tfile_url VARCHAR(500) NOT NULL, \n\tuploaded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(task_id) REFERENCES tasks (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS task_comments (\n\tid VARCHAR NOT NULL, \n\ttask_id VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\tcomment TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(task_id) REFERENCES tasks (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS invoices (\n\tid VARCHAR NOT NULL, \n\torganization_id VARCHAR NOT NULL, \n\tquote_id VARCHAR, \n\tinvoice_number VARCHAR(100) NOT NULL, \n\tamount FLOAT NOT NULL, \n\tstatus VARCHAR(50) NOT NULL, \n\tdue_date TIMESTAMP WITH TIME ZONE NOT NULL, \n\tstripe_checkout_url VARCHAR(500), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(quote_id) REFERENCES quotes (id) ON DELETE SET NULL\n)",
    "CREATE TABLE IF NOT EXISTS quote_items (\n\tid VARCHAR NOT NULL, \n\tquote_id VARCHAR NOT NULL, \n\tproduct_id VARCHAR NOT NULL, \n\tquantity INTEGER NOT NULL, \n\tunit_price FLOAT NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(quote_id) REFERENCES quotes (id) ON DELETE CASCADE, \n\tFOREIGN KEY(product_id) REFERENCES products (id) ON DELETE CASCADE\n)",
    "CREATE TABLE IF NOT EXISTS invoice_items (\n\tid VARCHAR NOT NULL, \n\tinvoice_id VARCHAR NOT NULL, \n\tproduct_id VARCHAR NOT NULL, \n\tquantity INTEGER NOT NULL, \n\tunit_price FLOAT NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(invoice_id) REFERENCES invoices (id) ON DELETE CASCADE, \n\tFOREIGN KEY(product_id) REFERENCES products (id) ON DELETE CASCADE\n)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_countries_name ON countries (name)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_currencies_code ON currencies (code)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_languages_code ON languages (code)",
    "CREATE INDEX IF NOT EXISTS ix_organizations_domain ON organizations (domain)",
    "CREATE INDEX IF NOT EXISTS ix_permissions_module ON permissions (module)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_settings_key ON settings (key)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_timezones_name ON timezones (name)",
    "CREATE INDEX IF NOT EXISTS ix_user_invitations_email ON user_invitations (email)",
    "CREATE INDEX IF NOT EXISTS ix_user_invitations_organization_id ON user_invitations (organization_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_user_invitations_token ON user_invitations (token)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_api_keys_key_hash ON api_keys (key_hash)",
    "CREATE INDEX IF NOT EXISTS ix_api_keys_organization_id ON api_keys (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_companies_industry ON companies (industry)",
    "CREATE INDEX IF NOT EXISTS ix_companies_organization_id ON companies (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_contacts_company_id ON contacts (company_id)",
    "CREATE INDEX IF NOT EXISTS ix_contacts_email ON contacts (email)",
    "CREATE INDEX IF NOT EXISTS ix_contacts_organization_id ON contacts (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_deal_stages_organization_id ON deal_stages (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_email_templates_organization_id ON email_templates (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_emails_organization_id ON emails (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_emails_to_email ON emails (to_email)",
    "CREATE INDEX IF NOT EXISTS ix_integrations_organization_id ON integrations (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_lead_sources_organization_id ON lead_sources (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_lead_statuses_organization_id ON lead_statuses (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_meetings_organization_id ON meetings (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_organization_settings_organization_id ON organization_settings (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_organization_subscriptions_organization_id ON organization_subscriptions (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_product_categories_organization_id ON product_categories (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_roles_organization_id ON roles (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_states_country_id ON states (country_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)",
    "CREATE INDEX IF NOT EXISTS ix_users_organization_id ON users (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_webhooks_organization_id ON webhooks (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_activity_logs_module ON activity_logs (module)",
    "CREATE INDEX IF NOT EXISTS ix_activity_logs_organization_id ON activity_logs (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_activity_logs_user_id ON activity_logs (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_ai_conversations_user_id ON ai_conversations (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_ai_generated_contents_user_id ON ai_generated_contents (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_ai_meeting_summaries_meeting_id ON ai_meeting_summaries (meeting_id)",
    "CREATE INDEX IF NOT EXISTS ix_audit_logs_action ON audit_logs (action)",
    "CREATE INDEX IF NOT EXISTS ix_audit_logs_organization_id ON audit_logs (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_audit_logs_user_id ON audit_logs (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_calendar_events_user_id ON calendar_events (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_call_logs_contact_id ON call_logs (contact_id)",
    "CREATE INDEX IF NOT EXISTS ix_call_logs_organization_id ON call_logs (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_cities_state_id ON cities (state_id)",
    "CREATE INDEX IF NOT EXISTS ix_company_contacts_company_id ON company_contacts (company_id)",
    "CREATE INDEX IF NOT EXISTS ix_company_contacts_contact_id ON company_contacts (contact_id)",
    "CREATE INDEX IF NOT EXISTS ix_contact_addresses_contact_id ON contact_addresses (contact_id)",
    "CREATE INDEX IF NOT EXISTS ix_contact_tags_contact_id ON contact_tags (contact_id)",
    "CREATE INDEX IF NOT EXISTS ix_contact_tags_tag_name ON contact_tags (tag_name)",
    "CREATE INDEX IF NOT EXISTS ix_deals_assigned_to ON deals (assigned_to)",
    "CREATE INDEX IF NOT EXISTS ix_deals_organization_id ON deals (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_deals_stage ON deals (stage)",
    "CREATE INDEX IF NOT EXISTS ix_documents_folder_id ON documents (folder_id)",
    "CREATE INDEX IF NOT EXISTS ix_documents_organization_id ON documents (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_email_logs_email_id ON email_logs (email_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_email_verifications_token ON email_verifications (token)",
    "CREATE INDEX IF NOT EXISTS ix_email_verifications_user_id ON email_verifications (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_leads_assigned_to ON leads (assigned_to)",
    "CREATE INDEX IF NOT EXISTS ix_leads_email ON leads (email)",
    "CREATE INDEX IF NOT EXISTS ix_leads_organization_id ON leads (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_leads_status ON leads (status)",
    "CREATE INDEX IF NOT EXISTS ix_meeting_attendees_meeting_id ON meeting_attendees (meeting_id)",
    "CREATE INDEX IF NOT EXISTS ix_notes_entity_id ON notes (entity_id)",
    "CREATE INDEX IF NOT EXISTS ix_notes_entity_type ON notes (entity_type)",
    "CREATE INDEX IF NOT EXISTS ix_notes_organization_id ON notes (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_notifications_is_read ON notifications (is_read)",
    "CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_otp_verifications_user_id ON otp_verifications (user_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_password_resets_token ON password_resets (token)",
    "CREATE INDEX IF NOT EXISTS ix_password_resets_user_id ON password_resets (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_products_category_id ON products (category_id)",
    "CREATE INDEX IF NOT EXISTS ix_products_organization_id ON products (organization_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_products_sku ON products (sku)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_tokens_token ON refresh_tokens (token)",
    "CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id ON refresh_tokens (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_report_exports_organization_id ON report_exports (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_role_permissions_permission_id ON role_permissions (permission_id)",
    "CREATE INDEX IF NOT EXISTS ix_role_permissions_role_id ON role_permissions (role_id)",
    "CREATE INDEX IF NOT EXISTS ix_tasks_assigned_to ON tasks (assigned_to)",
    "CREATE INDEX IF NOT EXISTS ix_tasks_organization_id ON tasks (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_tasks_status ON tasks (status)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_user_profiles_user_id ON user_profiles (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_user_roles_role_id ON user_roles (role_id)",
    "CREATE INDEX IF NOT EXISTS ix_user_roles_user_id ON user_roles (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_user_sessions_user_id ON user_sessions (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_ai_lead_scores_lead_id ON ai_lead_scores (lead_id)",
    "CREATE INDEX IF NOT EXISTS ix_ai_prompts_conversation_id ON ai_prompts (conversation_id)",
    "CREATE INDEX IF NOT EXISTS ix_deal_activities_deal_id ON deal_activities (deal_id)",
    "CREATE INDEX IF NOT EXISTS ix_deal_products_deal_id ON deal_products (deal_id)",
    "CREATE INDEX IF NOT EXISTS ix_deal_products_product_id ON deal_products (product_id)",
    "CREATE INDEX IF NOT EXISTS ix_document_versions_document_id ON document_versions (document_id)",
    "CREATE INDEX IF NOT EXISTS ix_lead_activities_lead_id ON lead_activities (lead_id)",
    "CREATE INDEX IF NOT EXISTS ix_lead_attachments_lead_id ON lead_attachments (lead_id)",
    "CREATE INDEX IF NOT EXISTS ix_lead_notes_lead_id ON lead_notes (lead_id)",
    "CREATE INDEX IF NOT EXISTS ix_lead_scores_lead_id ON lead_scores (lead_id)",
    "CREATE INDEX IF NOT EXISTS ix_lead_tags_lead_id ON lead_tags (lead_id)",
    "CREATE INDEX IF NOT EXISTS ix_lead_tags_tag_name ON lead_tags (tag_name)",
    "CREATE INDEX IF NOT EXISTS ix_quotes_deal_id ON quotes (deal_id)",
    "CREATE INDEX IF NOT EXISTS ix_quotes_organization_id ON quotes (organization_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_quotes_quote_number ON quotes (quote_number)",
    "CREATE INDEX IF NOT EXISTS ix_quotes_status ON quotes (status)",
    "CREATE INDEX IF NOT EXISTS ix_task_attachments_task_id ON task_attachments (task_id)",
    "CREATE INDEX IF NOT EXISTS ix_task_comments_task_id ON task_comments (task_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_invoices_invoice_number ON invoices (invoice_number)",
    "CREATE INDEX IF NOT EXISTS ix_invoices_organization_id ON invoices (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_invoices_status ON invoices (status)",
    "CREATE INDEX IF NOT EXISTS ix_quote_items_product_id ON quote_items (product_id)",
    "CREATE INDEX IF NOT EXISTS ix_quote_items_quote_id ON quote_items (quote_id)",
    "CREATE INDEX IF NOT EXISTS ix_invoice_items_invoice_id ON invoice_items (invoice_id)",
    "CREATE INDEX IF NOT EXISTS ix_invoice_items_product_id ON invoice_items (product_id)",
]


def upgrade() -> None:
    """Create the complete schema expected by later migrations."""
    for statement in _BASELINE_DDL:
        op.execute(statement)


def downgrade() -> None:
    """Keep the historical baseline downgrade non-destructive."""
    pass
