"""add setting system

Revision ID: 8b6bf297e2b8
Revises: f18d96a9fd11
Create Date: 2026-08-07 05:19:34.649645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6bf297e2b8'
down_revision: Union[str, Sequence[str], None] = 'f18d96a9fd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_fields_entity_type'), 'custom_fields', ['entity_type'], unique=False)
    op.create_index(op.f('ix_custom_fields_organization_id'), 'custom_fields', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_fields_organization_id'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_entity_type'), table_name='custom_fields')
    op.drop_table('custom_fields')
    # ### end Alembic commands ###
