"""update permission model

Revision ID: cdbf23cfb64c
Revises: 39346817277b
Create Date: 2026-08-05 14:21:09.223832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdbf23cfb64c'
down_revision: Union[str, Sequence[str], None] = '39346817277b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('key', sa.String(length=150), nullable=False))
    op.add_column('permissions', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('permissions', sa.Column('category', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.create_index(op.f('ix_permissions_category'), 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=True)
    op.drop_column('permissions', 'module')
    op.drop_column('permissions', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('permissions', sa.Column('module', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_category'), table_name='permissions')
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.drop_column('permissions', 'category')
    op.drop_column('permissions', 'name')
    op.drop_column('permissions', 'key')
    # ### end Alembic commands ###
