"""add organization invitations

Revision ID: f18d96a9fd11
Revises: 4accd07da9c5
Create Date: 2026-08-06 11:07:19.146398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18d96a9fd11'
down_revision: Union[str, Sequence[str], None] = '4accd07da9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_invitations', 'organization_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_invitations', 'organization_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
