"""update integration api key webhook models

Revision ID: f82b2e1191f0
Revises: 7999f13a9ce6
Create Date: 2026-08-07 06:23:06.780755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82b2e1191f0'
down_revision: Union[str, Sequence[str], None] = '7999f13a9ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('api_keys', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('integrations', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('integrations', sa.Column('webhook_url', sa.Text(), nullable=True))
    op.add_column('integrations', sa.Column('credentials', sa.Text(), nullable=True))
    op.add_column('integrations', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('integrations', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('integrations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    op.add_column('webhooks', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('webhooks', sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('webhooks', sa.Column('failure_count', sa.Integer(), nullable=False))
    op.add_column('webhooks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'updated_at')
    op.drop_column('webhooks', 'failure_count')
    op.drop_column('webhooks', 'last_triggered_at')
    op.drop_column('webhooks', 'name')
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.drop_column('integrations', 'updated_at')
    op.drop_column('integrations', 'last_error')
    op.drop_column('integrations', 'status')
    op.drop_column('integrations', 'credentials')
    op.drop_column('integrations', 'webhook_url')
    op.drop_column('integrations', 'provider')
    op.drop_column('api_keys', 'updated_at')
    op.drop_column('api_keys', 'expires_at')
    # ### end Alembic commands ###
