"""add missing organization columns

Revision ID: f8a832876815
Revises: 7fcd8359c9f2
Create Date: 2026-08-03 21:43:19.408591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a832876815'
down_revision: Union[str, Sequence[str], None] = '7fcd8359c9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('company_size', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('postal_code', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('organizations', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('tax_number', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'registration_number')
    op.drop_column('organizations', 'tax_number')
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'language')
    op.drop_column('organizations', 'currency')
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'postal_code')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'company_size')
    op.drop_column('organizations', 'industry')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'slug')
    op.drop_column('leads', 'postal_code')
    op.drop_column('leads', 'address')
    op.drop_column('leads', 'city')
    op.drop_column('leads', 'state')
    op.drop_column('leads', 'country')
    op.drop_column('leads', 'company_size')
    op.drop_column('leads', 'industry')
    op.drop_column('leads', 'website')
    # ### end Alembic commands ###
