'use client';
import Link from 'next/link';
import { BarChart3, LineChart as LineChartIcon } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui';
import type { FunnelStageItem, LeadConversionItem, RevenueChart } from '@/lib/api/dashboard';
import { DashboardSectionEmpty, DashboardSectionError, DashboardSectionSkeleton } from './dashboard-section-state';

function ChartHeader({ icon: Icon, title, description, href, linkLabel }: { icon: typeof BarChart3; title: string; description: string; href: string; linkLabel: string }) { return <CardHeader className="flex-row items-start justify-between gap-4 border-b border-slate-100 p-4 sm:p-5"><div className="flex min-w-0 gap-2.5"><Icon className="mt-0.5 size-4 shrink-0 text-blue-600" aria-hidden="true" /><div><CardTitle className="text-sm">{title}</CardTitle><CardDescription className="mt-1 text-xs">{description}</CardDescription></div></div><Link href={href} className="shrink-0 rounded text-xs font-semibold text-blue-600 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500">{linkLabel}</Link></CardHeader>; }

export function RevenueTrendCard({ data, isLoading, isError, onRetry, formatCurrency }: { data?: RevenueChart; isLoading: boolean; isError: boolean; onRetry: () => void; formatCurrency: (value: number) => string }) {
  const chartData = data?.months.map((month, index) => ({ month, revenue: data.actual[index] })) ?? [];
  return <Card className="min-w-0 shadow-none"><ChartHeader icon={LineChartIcon} title="Won revenue trend" description="Revenue from deals closed won in the selected period" href="/deals" linkLabel="View deals" /><CardContent className="p-4 sm:p-5">{isLoading && <DashboardSectionSkeleton />}{isError && <DashboardSectionError message="Revenue trend could not be loaded." onRetry={onRetry} />}{!isLoading && !isError && chartData.length === 0 && <DashboardSectionEmpty title="No won revenue yet" description="Closed-won opportunities in this period will appear here." />}{!isLoading && !isError && chartData.length > 0 && <><div className="h-64 w-full" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} width={58} tick={{ fill: '#64748b', fontSize: 11 }} tickFormatter={(value) => new Intl.NumberFormat(undefined, { notation: 'compact' }).format(Number(value))} /><Tooltip formatter={(value) => [formatCurrency(Number(value)), 'Won revenue']} contentStyle={{ borderRadius: 10, borderColor: '#e2e8f0', fontSize: 12 }} /><Line type="monotone" dataKey="revenue" stroke="#2563eb" strokeWidth={2.5} dot={{ r: 3, fill: '#fff', strokeWidth: 2 }} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer></div><table className="sr-only"><caption>Won revenue by month</caption><thead><tr><th>Month</th><th>Revenue</th></tr></thead><tbody>{chartData.map((item) => <tr key={item.month}><td>{item.month}</td><td>{formatCurrency(item.revenue)}</td></tr>)}</tbody></table></>}</CardContent></Card>;
}

export function PipelineCard({ data, isLoading, isError, onRetry, formatCurrency }: { data: FunnelStageItem[]; isLoading: boolean; isError: boolean; onRetry: () => void; formatCurrency: (value: number) => string }) {
  const stages = data.filter((stage) => !stage.stage.toLowerCase().includes('lost')); const maximum = Math.max(...stages.map((stage) => stage.value), 0);
  return <Card className="min-w-0 shadow-none"><ChartHeader icon={BarChart3} title="Sales pipeline" description="Current opportunity value by stage" href="/pipelines" linkLabel="Open pipeline" /><CardContent className="space-y-4 p-4 sm:p-5">{isLoading && <DashboardSectionSkeleton />}{isError && <DashboardSectionError message="Sales pipeline could not be loaded." onRetry={onRetry} />}{!isLoading && !isError && stages.every((stage) => stage.count === 0) && <DashboardSectionEmpty title="No active pipeline" description="Create an opportunity to start tracking pipeline movement." />}{!isLoading && !isError && stages.some((stage) => stage.count > 0) && stages.map((stage) => { const width = maximum > 0 ? Math.max((stage.value / maximum) * 100, stage.value > 0 ? 3 : 0) : 0; return <div key={stage.stage}><div className="mb-1.5 flex items-center justify-between gap-3 text-xs"><span className="truncate font-semibold text-slate-700">{stage.stage} <span className="font-normal text-slate-400">({stage.count})</span></span><span className="shrink-0 font-semibold text-slate-900 tabular-nums">{formatCurrency(stage.value)}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${width}%` }} role="progressbar" aria-label={`${stage.stage} pipeline value`} aria-valuemin={0} aria-valuemax={maximum} aria-valuenow={stage.value} /></div></div>; })}</CardContent></Card>;
}

export function LeadConversionCard({ data, isLoading, isError, onRetry }: { data: LeadConversionItem[]; isLoading: boolean; isError: boolean; onRetry: () => void }) { return <Card className="shadow-none"><ChartHeader icon={BarChart3} title="Lead channels" description="Volume and conversion by acquisition source" href="/leads" linkLabel="View leads" /><CardContent className="p-4 sm:p-5">{isLoading && <DashboardSectionSkeleton className="h-40" />}{isError && <DashboardSectionError message="Lead channel data could not be loaded." onRetry={onRetry} />}{!isLoading && !isError && data.length === 0 && <DashboardSectionEmpty title="No lead-source data" description="Lead acquisition channels will appear as leads are created." />}{!isLoading && !isError && data.length > 0 && <div className="space-y-3">{data.slice(0, 5).map((item) => <div key={item.source} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3"><div className="min-w-0"><div className="flex justify-between gap-3 text-xs"><span className="truncate font-semibold text-slate-700">{item.source}</span><span className="text-slate-500">{item.leads} leads</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${item.rate}%` }} /></div></div><span className="w-12 text-right text-xs font-bold text-slate-900 tabular-nums">{item.rate}%</span></div>)}</div>}</CardContent></Card>; }
