import Link from 'next/link';
import { CheckSquare2, Mail, PhoneCall, Users, Video } from 'lucide-react';
import { Avatar, AvatarFallback, Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui';
import type { ActivityItem } from '@/lib/api/activities';
import type { ContactItem } from '@/lib/api/contacts';
import type { ActivitiesSummary, TopPerformerItem } from '@/lib/api/dashboard';
import { DashboardSectionEmpty, DashboardSectionError, DashboardSectionSkeleton } from './dashboard-section-state';

function Header({ title, description, href }: { title: string; description: string; href: string }) { return <CardHeader className="flex-row items-start justify-between gap-3 border-b border-slate-100 p-4"><div><CardTitle className="text-sm">{title}</CardTitle><CardDescription className="mt-1 text-xs">{description}</CardDescription></div><Link href={href} className="shrink-0 rounded text-xs font-semibold text-blue-600 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500">See all</Link></CardHeader>; }
export function ActivitySummaryCard({ data, isLoading, isError, onRetry }: { data?: ActivitiesSummary; isLoading: boolean; isError: boolean; onRetry: () => void }) {
  const items = data ? [{ label: 'Calls', value: data.calls_completed, icon: PhoneCall, color: 'text-blue-600' }, { label: 'Emails', value: data.emails_sent, icon: Mail, color: 'text-indigo-600' }, { label: 'Meetings', value: data.meetings_held, icon: Video, color: 'text-violet-600' }, { label: 'Tasks', value: data.tasks_completed, icon: CheckSquare2, color: 'text-emerald-600' }] : [];
  return <Card className="shadow-none"><CardHeader className="border-b border-slate-100 p-4"><CardTitle className="text-sm">Activity summary</CardTitle><CardDescription className="text-xs">{data?.period_label ?? 'Selected period'}</CardDescription></CardHeader><CardContent className="p-0">{isLoading && <DashboardSectionSkeleton className="h-28 rounded-none" />}{isError && <DashboardSectionError message="Activity totals could not be loaded." onRetry={onRetry} />}{data && <div className="grid grid-cols-2">{items.map(({ label, value, icon: Icon, color }, index) => <div key={label} className={`flex items-center gap-2.5 border-slate-100 p-3.5 ${index % 2 ? 'border-l' : ''} ${index > 1 ? 'border-t' : ''}`}><Icon className={`size-4 ${color}`} /><div><p className="text-[11px] text-slate-500">{label}</p><p className="text-base font-bold text-slate-900 tabular-nums">{value}</p></div></div>)}</div>}</CardContent></Card>;
}
export function RecentContactsCard({ contacts, isLoading, isError, onRetry }: { contacts: ContactItem[]; isLoading: boolean; isError: boolean; onRetry: () => void }) { return <Card className="shadow-none"><Header title="Recent contacts" description="Newest customer relationships" href="/contacts" /><CardContent className="p-2">{isLoading && <DashboardSectionSkeleton className="h-48" />}{isError && <DashboardSectionError message="Recent contacts could not be loaded." onRetry={onRetry} />}{!isLoading && !isError && contacts.length === 0 && <DashboardSectionEmpty title="No contacts yet" description="New contacts will appear here." />}{!isLoading && !isError && contacts.map((contact) => <Link key={contact.id} href={`/contacts/${contact.id}`} className="flex items-center gap-3 rounded-lg px-2.5 py-2 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"><Avatar className="size-8"><AvatarFallback className="bg-blue-50 text-[11px] font-bold text-blue-700">{contact.name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase()}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-900">{contact.name}</p><p className="truncate text-[11px] text-slate-500">{contact.position || contact.email}</p></div></Link>)}</CardContent></Card>; }
export function RecentActivityCard({ activities, isLoading, isError, onRetry }: { activities: ActivityItem[]; isLoading: boolean; isError: boolean; onRetry: () => void }) { return <Card className="shadow-none"><Header title="Recent activity" description="Latest updates across CRM" href="/activities" /><CardContent className="p-3">{isLoading && <DashboardSectionSkeleton className="h-56" />}{isError && <DashboardSectionError message="Recent activity could not be loaded." onRetry={onRetry} />}{!isLoading && !isError && activities.length === 0 && <DashboardSectionEmpty title="No recent activity" description="Updates across permitted modules will appear here." />}{!isLoading && !isError && <ol className="space-y-1">{activities.map((activity) => <li key={activity.id}><Link href={activity.href} className="group flex gap-3 rounded-lg p-2 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"><span className="mt-1.5 size-2 shrink-0 rounded-full bg-blue-500 ring-4 ring-blue-50" /><span className="min-w-0"><span className="block truncate text-xs font-semibold text-slate-800 group-hover:text-blue-700">{activity.action}</span><span className="mt-0.5 line-clamp-2 block text-[11px] leading-4 text-slate-500">{activity.description || activity.entity_type}</span><time className="mt-1 block text-[10px] text-slate-400" dateTime={activity.occurred_at}>{new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(activity.occurred_at))}</time></span></Link></li>)}</ol>}</CardContent></Card>; }
export function TopPerformersCard({ performers, isLoading, isError, onRetry, formatCurrency }: { performers: TopPerformerItem[]; isLoading: boolean; isError: boolean; onRetry: () => void; formatCurrency: (value: number) => string }) { return <Card className="shadow-none"><CardHeader className="border-b border-slate-100 p-4"><CardTitle className="flex items-center gap-2 text-sm"><Users className="size-4 text-amber-600" />Top performers</CardTitle><CardDescription className="text-xs">Closed-won revenue for this period</CardDescription></CardHeader><CardContent className="p-2">{isLoading && <DashboardSectionSkeleton className="h-40" />}{isError && <DashboardSectionError message="Top performers could not be loaded." onRetry={onRetry} />}{!isLoading && !isError && performers.length === 0 && <DashboardSectionEmpty title="No won deals yet" description="Closed-won team performance will appear here." />}{!isLoading && !isError && performers.length > 0 && <div className="space-y-1">{performers.slice(0, 4).map((item, index) => <div key={item.name} className="flex items-center gap-3 rounded-lg px-2.5 py-2"><span className="w-4 text-center text-[11px] font-bold text-slate-400">{index + 1}</span><Avatar className="size-8"><AvatarFallback className="bg-amber-50 text-[11px] font-bold text-amber-700">{item.avatar}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-900">{item.name}</p><p className="text-[11px] text-slate-500">{item.deals_count} won</p></div><span className="text-xs font-bold text-emerald-700 tabular-nums">{formatCurrency(item.revenue)}</span></div>)}</div>}</CardContent></Card>; }
