import { fireEvent, render, screen } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({ replace: vi.fn(), invalidate: vi.fn().mockResolvedValue(undefined), permissions: new Set<string>(), kpis: vi.fn(), revenue: vi.fn(), funnel: vi.fn(), conversions: vi.fn(), summary: vi.fn(), deals: vi.fn(), performers: vi.fn(), ai: vi.fn(), widgets: vi.fn(), save: vi.fn() }));
const result = <T,>(data: T, extra = {}) => ({ data, isLoading: false, isError: false, isFetching: false, refetch: vi.fn(), ...extra });
vi.mock('next/navigation', () => ({ useRouter: () => ({ replace: mocks.replace }), usePathname: () => '/dashboard', useSearchParams: () => new URLSearchParams('range=30d') }));
vi.mock('@tanstack/react-query', async (importOriginal) => { const actual = await importOriginal<typeof import('@tanstack/react-query')>(); return { ...actual, useQueryClient: () => ({ invalidateQueries: mocks.invalidate }), useQuery: ({ queryKey }: { queryKey: string[] }) => queryKey[0] === 'contacts' ? result([{ id: 'contact-1', name: 'Ada Lovelace', email: 'ada@example.com', position: 'CTO' }]) : result({ items: [{ id: 'deals:event-1', module: 'deals', action: 'Stage updated', description: 'Enterprise renewal', entity_type: 'deal', entity_id: 'deal-1', occurred_at: '2026-09-15T10:00:00Z', href: '/deals/deal-1' }], total: 1 }) }; });
vi.mock('@/hooks/use-has-permission', () => ({ useHasPermission: () => ({ hasPermission: (permission: string) => mocks.permissions.has(permission) }) }));
vi.mock('@/lib/api/dashboard', () => ({ DEFAULT_DASHBOARD_CURRENCY: 'INR', DEFAULT_DASHBOARD_LOCALE: 'en-IN', dashboardQueryKeys: { all: ['dashboard'] }, useDashboardKpisQuery: (...args: unknown[]) => mocks.kpis(...args), useRevenueChartQuery: () => mocks.revenue(), useSalesFunnelQuery: () => mocks.funnel(), useLeadConversionsQuery: () => mocks.conversions(), useActivitiesSummaryQuery: () => mocks.summary(), useRecentDealsQuery: () => mocks.deals(), useTopPerformersQuery: () => mocks.performers(), useDashboardAiInsightsQuery: (...args: unknown[]) => mocks.ai(...args), useCustomWidgetsQuery: () => mocks.widgets(), useSaveCustomWidgetsMutation: () => ({ mutateAsync: mocks.save, isPending: false }) }));
vi.mock('recharts', () => ({ ResponsiveContainer: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, LineChart: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, Line: () => null, CartesianGrid: () => null, Tooltip: () => null, XAxis: () => null, YAxis: () => null }));
import { DashboardView } from './dashboard-view';

describe('DashboardView', () => {
  beforeEach(() => {
    vi.clearAllMocks(); mocks.permissions = new Set(['contacts:read', 'activities:read', 'deals:read', 'dashboard:customize']);
    mocks.kpis.mockReturnValue(result({ total_leads: 12, deals_won_amount: 9000, pipeline_revenue: 22000, win_rate_percentage: 50, won_deals_count: 2, closed_deals_count: 4, ai_lead_score_avg: 70, scored_leads_count: 10, quote_count: 3, quote_value: 12000, quote_conversion_percentage: 50, invoice_count: 2, invoice_total: 8000, paid_amount: 6000, outstanding_amount: 2000, pending_payment_count: 1, partially_paid_invoice_count: 0, paid_invoice_count: 1, revenue: 6000, collection_rate_percentage: 75, currency: 'INR', locale: 'en-IN', recent_activity: [], comparisons: { total_leads: { previous_value: 10, change_percentage: 20 }, deals_won_amount: { previous_value: 6000, change_percentage: 50 }, won_deals_count: { previous_value: 1, change_percentage: 100 }, win_rate_percentage: { previous_value: 25, change_percentage: 100 }, quote_value: { previous_value: 8000, change_percentage: 50 }, revenue: { previous_value: 5000, change_percentage: 20 } } }));
    mocks.revenue.mockReturnValue(result({ months: ['Sep 2026'], actual: [9000], target: [] })); mocks.funnel.mockReturnValue(result([{ stage: 'Proposal', count: 2, value: 22000 }])); mocks.conversions.mockReturnValue(result([{ source: 'LinkedIn', leads: 10, converted: 4, rate: 40 }])); mocks.summary.mockReturnValue(result({ calls_completed: 2, emails_sent: 4, meetings_held: 1, tasks_completed: 3, period_label: 'Selected period · UTC' })); mocks.deals.mockReturnValue(result([{ deal_id: 'deal-1', title: 'Enterprise renewal', amount: 9000, stage: 'Proposal', owner: 'Grace Hopper', updated_at: '2026-09-15' }])); mocks.performers.mockReturnValue(result([])); mocks.ai.mockReturnValue(result(undefined)); mocks.widgets.mockReturnValue(result([]));
  });
  it('renders real metrics and permission-aware panels', () => { render(<DashboardView />); expect(screen.getByText('Sales dashboard')).toBeInTheDocument(); expect(screen.getAllByText('₹22,000')).not.toHaveLength(0); expect(screen.getByText('Increased 20% vs previous period')).toBeInTheDocument(); expect(screen.getByText('Won revenue trend')).toBeInTheDocument(); expect(screen.getByText('Ada Lovelace')).toBeInTheDocument(); expect(screen.getByText('Stage updated')).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Enterprise renewal' })).toHaveAttribute('href', '/deals/deal-1'); expect(screen.getByRole('link', { name: 'Open deals' })).toHaveAttribute('href', '/deals'); });
  it('passes the URL range to period-aware queries', () => { render(<DashboardView />); const range = mocks.kpis.mock.calls[0][0]; expect(new Date(range.endAt).getTime() - new Date(range.startAt).getTime()).toBe(30 * 86400000); });
  it('renders errors with retry', () => { mocks.revenue.mockReturnValue(result(undefined, { isError: true })); render(<DashboardView />); expect(screen.getByRole('alert')).toHaveTextContent('Revenue trend could not be loaded'); expect(screen.getByRole('button', { name: 'Try again' })).toBeInTheDocument(); });
  it('hides permission-gated content', () => { mocks.permissions = new Set(); render(<DashboardView />); expect(screen.queryByRole('link', { name: 'Open deals' })).not.toBeInTheDocument(); expect(screen.queryByText('Recent contacts')).not.toBeInTheDocument(); expect(screen.queryByText('Recent activity')).not.toBeInTheDocument(); });
  it('does not request or reveal deal-derived AI insights without deal read access', () => { mocks.permissions = new Set(['ai:generate']); mocks.ai.mockReturnValue(result({ summary: 'Restricted deal', risk_deals: [{ id: 'deal-secret', title: 'Secret renewal', stage: 'Negotiation', updated_at: '2026-09-15' }] })); render(<DashboardView />); expect(mocks.ai.mock.calls[0][0]).toMatchObject({ enabled: false }); expect(screen.queryByText('Secret renewal')).not.toBeInTheDocument(); expect(screen.queryByText('AI pipeline briefing')).not.toBeInTheDocument(); });
  it('does not request widget data until preferences resolve', () => { mocks.widgets.mockReturnValue(result([], { isLoading: true })); render(<DashboardView />); expect(mocks.kpis.mock.calls[0][1]).toMatchObject({ enabled: false }); });
  it('shows recoverable performer and AI failures', () => { mocks.permissions.add('ai:generate'); mocks.performers.mockReturnValue(result(undefined, { isError: true })); mocks.ai.mockReturnValue(result(undefined, { isError: true })); render(<DashboardView />); expect(screen.getByText('Top performers could not be loaded.')).toBeInTheDocument(); expect(screen.getByText('AI pipeline briefing could not be loaded.')).toBeInTheDocument(); });
  it('preserves actionable AI recommendations and risk-deal navigation', () => { mocks.permissions.add('ai:generate'); mocks.ai.mockReturnValue(result({ summary: 'Two deals need attention.', insights: [{ title: 'Follow up', description: 'Contact the buyer today.', type: 'warning', action: 'Follow Up', deal_id: 'deal-2' }], risk_deals: [{ id: 'deal-3', title: 'Renewal', amount: 5000, stage: 'Negotiation', probability: 35, updated_at: '2026-09-15' }] })); render(<DashboardView />); expect(screen.getByRole('link', { name: 'Follow Up' })).toHaveAttribute('href', '/deals/deal-2'); expect(screen.getByRole('link', { name: 'Renewal · Negotiation' })).toHaveAttribute('href', '/deals/deal-3'); });
  it('shows widget-save failures inside the open dialog', async () => { mocks.save.mockRejectedValueOnce(new Error('save failed')); render(<DashboardView />); fireEvent.click(screen.getByRole('button', { name: 'Customize' })); fireEvent.click(screen.getByRole('button', { name: 'Save preferences' })); expect(await screen.findByRole('alert')).toHaveTextContent('Dashboard preferences could not be saved'); expect(screen.getByRole('dialog')).toBeInTheDocument(); });
  it('filters the deals preview', () => { render(<DashboardView />); fireEvent.change(screen.getByPlaceholderText('Search deals or owners...'), { target: { value: 'missing' } }); expect(screen.getByText('No deals found')).toBeInTheDocument(); });
});
